### ISSUE TITLE
Add in resource attribute for which step we are on

### ISSUE THREAD

**Issue by McSick** [honeycombio/workshop-advanced-instrumentation#17]
It would be good to know which step generated data in honeycomb. A simple resource attribute should be used here like "02-asynchronous" , "03-span-links"

**Comment by puckpuck** [comment]
We can do this using the `OTEL_RESOURCE_ATTRIBUTE`S environment variable. And we should also update to use `OTEL_SERVICE_NAME` properly as well. Not all docs go about it that way, but all SDKs should support using environment variables to set these things up.

This would also need to include instructions (slides and/or readme) to cover the `OTEL_*` environment variables.

**Comment by puckpuck** [comment]
Solved with the with [56cfa1e](https://github.com/honeycombio/workshop-advanced-instrumentation/commit/56cfa1ebd0fa4d0f5e16999c3502c0839cb123ca)
